#!/bin/bash
#
#	/etc/rc.d/init.d/mysqld_exporter
#
# chkconfig: 2345 80 80
#
# config: /etc/prometheus/mysqld_exporter.conf
# pidfile: /var/run/prometheus/mysqld_exporter.pid

# Source function library.
. /etc/init.d/functions


RETVAL=0
PROG="mysqld_exporter"
DAEMON_SYSCONFIG=/etc/sysconfig/${PROG}
DAEMON=/usr/local/bin/mysqld_exporter
PID_FILE=/var/run/${PROG}.pid
LOCK_FILE=/var/lock/subsys/${PROG}
LOG_FILE=/var/log/${PROG}/${PROG}.log
DAEMON_USER="mysqld_exporter"
FQDN=$(hostname --long)
GOMAXPROCS=$(grep -c ^processor /proc/cpuinfo)

# Requires DB user:
# CREATE USER 'exporter'@'localhost' IDENTIFIED BY 'XXXXXXXX' WITH MAX_USER_CONNECTIONS 3;
# GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'localhost';

export DATA_SOURCE_NAME='user:pw@(localhost:3306)/'

[ -f ${DAEMON_SYSCONFIG} ] && . ${DAEMON_SYSCONFIG}

start() {
  if check_status > /dev/null; then
    echo "${PROG} is already running"
    exit 0
  fi

  echo -n $"Starting ${PROG}: "
  daemonize -u ${DAEMON_USER} -p ${PID_FILE} -l ${LOCK_FILE} -a -e ${LOG_FILE} -o ${LOG_FILE} ${DAEMON} ${ARGS}
  RETVAL=$?
  echo ""
  return $RETVAL
}

stop() {
    echo -n $"Stopping ${PROG}: "
    killproc -p ${PID_FILE} -d 10 ${DAEMON}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${LOCK_FILE} ${PID_FILE}
    return $RETVAL
}  

check_status() {
    status -p ${PID_FILE} ${DAEMON}
    RETVAL=$?
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
	check_status
        ;;
    reload|force-reload)
        reload
        ;;
    restart)
        stop
        start
        ;;
    *)
        N=/etc/init.d/${NAME}
        echo "Usage: $N {start|stop|status|restart|force-reload}" >&2
        RETVAL=2
        ;;
esac

exit ${RETVAL}


